# Generated by Django 5.1 on 2024-08-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_text', models.CharField(max_length=200)),
                ('added_date', models.DateTimeField(verbose_name='date added')),
                ('is_done', models.BooleanField()),
            ],
        ),
    ]
